name: publish

on: [push]
#aaaaa
jobs:
  publish-iec61850-image:
    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the iec61850 Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u IWaheed --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
